Enhanced build with getopt.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,89 +1,140 @@
 #!/usr/bin/env bash
 
+fail()
+{
+    local message=${1:-"Something went wrong!"}
+    echo $message
+    exit 1
+}
+
+usage()
+{
+    cat <<EOF
+Usage: build [options]
+
+Options:
+
+    --prefix <prefix>       Installation prefix for LALSuite.
+    -c, --c                 Build C modules.
+    -p, --python            Build Python modules.
+    -s, --src <src-dir>     Build from <src-dir>.
+    -n, -nprocs <n>         Number of build processes to spawn.
+    -h, --help              Display this help message.
+EOF
+    exit 0
+}
+
+prog=$(basename "$0")
+options=$(getopt --name "$prog" --options hcps:n --longoptions help,c,python,prefix:,src:,nprocs -- $@ 2> /dev/null) || fail "Couldn't parse options."
+eval set -- "$options"
+while [[ $# > 0 ]]; do
+    case "$1" in
+        --prefix)
+            prefix=$2
+            shift;;
+        -c | --c)
+            buildc=true;;
+        -p | --python)
+            buildpython=true;;
+        -s | --src)
+            srcdir=$2
+            shift;;
+        -n | --nprocs)
+            nprocs=$2
+            shift;;
+        --cc)
+            cc=$2
+            shift;;
+        --flags)
+            flags=$2
+            shift;;
+        -h | --help)
+            usage;;
+        --)
+            shift
+            break;;
+    esac
+    shift
+done
+
 set -e
 
+# Check source directory and prefix.
+[[ -z $prefix ]] && fail "Prefix not specified!"
+[[ ! -d $srcdir ]] && fail "Invalid source directory!"
+srcdir=$(readlink -f $srcdir)
+
 # Remember script directory.
-SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-
-# Source directory
-if [[ ! -d $1 ]]; then
-    echo "Invalid source directory!"
-fi
-SRCDIR=$(readlink -f $1)
-
-# This is where LAL Suite will go.
-if [[ -z $LSCSOFT_ROOTDIR ]]; then
-    echo "LSCSOFT_ROOTDIR not specified!"
-    exit 1
-fi
-ROOTDIR=$LSCSOFT_ROOTDIR
+scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 #BRANCHNAME=$(basename $(git symbolic-ref HEAD))
 #echo "Installing lsc software from $BRANCHNAME branch."
-#ROOTDIR=$LSCSOFT_ROOTDIR/$BRANCHNAME
+#prefix=$LSCSOFT_ROOTDIR/$BRANCHNAME
 
-echo "Building from $SRCDIR; installing to $ROOTDIR."
-cd $SRCDIR
-
-# Number of parallel processes in make.
-NPROCS=4
-
-# Default CFLAGS. Use clang if it's available.
-CFLAGS="-march=native -g"
-if [[ -x $(which clang) ]]; then
-    CC=clang
+cflags="-march=native -g"
+if [[ -z $cc ]]; then
+    # User didn't specify CC at command line.
+    if [[ -x $(which clang) ]]; then
+        cc=clang
+    fi
 fi
 
 # Common flags to every configure process.
-COMMON_CONFIG_FLAGS="--enable-swig-python --enable-mpi --disable-laldetchar"
+if [[ -z $flags ]]; then
+    flags="--enable-swig-python --enable-mpi --disable-laldetchar"
+fi
+
+# Number of build processes.
+if [[ -z $nprocs ]]; then
+    nprocs=1
+fi
 
 # lscsoftrc location.
-RCFILE=$ROOTDIR/etc/lscsoftrc
+lscsoftrc=$prefix/etc/lscsoftrc
+
+echo "Installing to $prefix"
 
 make_c() {
+    cd $srcdir
+
+    echo "Building C modules from $srcdir"
     make distclean || true
     ./00boot
-    ./configure --prefix=$ROOTDIR $COMMON_CONFIG_FLAGS CC="$CC" CFLAGS="$CFLAGS"
-    make -j $NPROCS
+    ./configure --prefix=$prefix $flags CC="$cc" CFLAGS="$cflags"
+    make -j $nprocs
     make install
 
     # Generate lscsoftrc.
-    . $SCRIPTDIR/generate-rc $ROOTDIR $RCFILE
+    . $scriptdir/generate-rc $prefix $lscsoftrc
 }
 
 make_python() {
-    if [[ ! -f $RCFILE ]]; then
-        fail "Could not find $RCFILE."
-    fi
-    . $RCFILE
+    [[ ! -f $lscsoftrc ]] && fail "Could not find $lscsoftrc"
+    . $lscsoftrc
 
-    cd $SRCDIR/pylal
+    echo "Building $srcdir/pylal"
+    cd $srcdir/pylal
     rm -rf build
-    python setup.py install --prefix=$ROOTDIR
-    . $RCFILE
+    python setup.py install --prefix=$prefix
+    . $lscsoftrc
 
-    cd $SRCDIR/glue
+    echo "Building $srcdir/glue"
+    cd $srcdir/glue
     rm -rf build
-    python setup.py install --prefix=$ROOTDIR
-    . $RCFILE
+    python setup.py install --prefix=$prefix
+    . $lscsoftrc
 }
 
-shift
-if [ $# -lt 1 ]; then
+if [[ -z $buildc && -z $buildpython ]]; then
+    # Build both.
     make_c
     make_python
 else
-    while [ $# -ge 1 ]; do
-        case $1 in
-            c)
-                make_c;;
-            python)
-                make_python;;
-            *)
-                echo "Unrecognized argument \"$1\".  Usage:"
-                echo "build [c] [python]"
-                exit 1
-        esac
-        shift
-    done
+    if [[ $buildc ]]; then
+        make_c
+    fi
+
+    if [[ $buildpython ]]; then
+        make_python
+    fi
 fi
